# Generated by Django 5.1.3 on 2024-12-06 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('text_app', '0003_alter_tbltext_author_alter_tbltext_author2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblBigramDataset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Время создания объекта')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Время изменения объекта')),
                ('created_by', models.IntegerField(db_comment='Автор создания', default=0)),
                ('updated_by', models.IntegerField(db_comment='Автор обновления', default=0)),
                ('is_deleted', models.BooleanField(db_comment='Флаг удаления дерева', default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(db_comment='Название датасета', max_length=200)),
                ('is_public', models.BooleanField(db_comment='Публичный доступ к датасету', default=False)),
                ('max_bigrams', models.IntegerField(db_comment='Максимальное число биграмм в датасете', default=100)),
                ('min_occurrence', models.IntegerField(db_comment='Минимальное количество встречаемости биграммы', default=1)),
                ('is_use_initial', models.BooleanField(db_comment='расчет биграмм по словоформам (False) или по начальным значениям (True)', default=False)),
                ('is_sentence_split', models.BooleanField(db_comment='расчет биграмм по предложениям или по абзацам', default=True)),
                ('content', models.JSONField(db_comment='Перечень биграмм', default=list)),
                ('owner', models.ForeignKey(blank=True, db_column='owner', db_comment='Владелец датасета', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('text_group', models.ForeignKey(blank=True, db_column='text_group', db_comment='Группа текстов или все доступные тексты', null=True, on_delete=django.db.models.deletion.SET_NULL, to='text_app.tbltextlistdescription')),
            ],
            options={
                'db_table': 'r_bigram_dataset',
                'db_table_comment': 'Датасеты биграмм для групп текстов',
            },
        ),
    ]
