# Generated by Django 5.1.3 on 2024-12-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r_bigrams_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbigramdataset',
            name='build_at',
            field=models.DateTimeField(db_comment='Время последней сборки', default=None, null=True),
        ),
        migrations.AddField(
            model_name='tblbigramdataset',
            name='build_status',
            field=models.TextField(db_comment='Статус сборки', max_length=200, null=True),
        ),
    ]
