# Generated by Django 5.1.3 on 2025-02-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r_ngrams_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='tblbigramdataset',
            table_comment='Датасеты N-грамм для групп текстов',
        ),
        migrations.RenameField(
            model_name='tblbigramdataset',
            old_name='max_bigrams',
            new_name='max_ngrams'
        ),
        migrations.AlterField(
            model_name='tblbigramdataset',
            name='content',
            field=models.JSONField(db_comment='Перечень N-грамм', default=list),
        ),
        migrations.AlterField(
            model_name='tblbigramdataset',
            name='is_sentence_split',
            field=models.BooleanField(db_comment='расчет N-грамм по предложениям или по абзацам', default=True),
        ),
        migrations.AlterField(
            model_name='tblbigramdataset',
            name='is_use_initial',
            field=models.BooleanField(db_comment='расчет N-грамм по словоформам (False) или по начальным значениям (True)', default=False),
        ),
        migrations.AlterField(
            model_name='tblbigramdataset',
            name='min_occurrence',
            field=models.IntegerField(db_comment='Минимальное количество встречаемости N-граммы', default=1),
        ),
        migrations.AlterModelTable(
            name='tblbigramdataset',
            table='r_ngram_dataset',
        ),
    ]
