# Generated by Django 5.1.3 on 2025-02-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r_ngrams_app', '0002_alter_tblbigramdataset_table_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbigramdataset',
            name='ngram_size',
            field=models.IntegerField(db_comment='Размер N-граммы', db_default=2),
        ),
        migrations.AlterField(
            model_name='tblbigramdataset',
            name='max_ngrams',
            field=models.IntegerField(db_comment='Максимальное число N-грамм в датасете', default=100),
        ),
    ]
