# Generated by Django 5.0.3 on 2024-04-22 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('text_app', '0003_alter_tbltext_author_alter_tbltext_author2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TblTreeDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200)),
                ('public', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('block_size', models.IntegerField(default=0)),
                ('first_list', models.ForeignKey(db_column='first_list', on_delete=django.db.models.deletion.CASCADE, to='text_app.tbltextlistdescription')),
                ('owner', models.ForeignKey(blank=True, db_column='owner', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('second_list', models.ForeignKey(db_column='second_list', on_delete=django.db.models.deletion.CASCADE, to='text_app.tbltextlistdescription')),
            ],
            options={
                'db_table': 'r_tree_description',
            },
        ),
    ]
