# Generated by Django 5.0.4 on 2024-04-24 11:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r_tree_app', '0001_initial'),
        ('text_app', '0003_alter_tbltext_author_alter_tbltext_author2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='tbltreedescription',
            table_comment='Проекты деревьев решений',
        ),
        migrations.AddField(
            model_name='tbltreedescription',
            name='build_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tbltreedescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='Время создания объекта', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbltreedescription',
            name='created_by',
            field=models.IntegerField(db_comment='Автор создания', default=0),
        ),
        migrations.AddField(
            model_name='tbltreedescription',
            name='graph',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbltreedescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Время изменения объекта'),
        ),
        migrations.AddField(
            model_name='tbltreedescription',
            name='updated_by',
            field=models.IntegerField(db_comment='Автор обновления', default=0),
        ),
        migrations.AlterField(
            model_name='tbltreedescription',
            name='first_list',
            field=models.ForeignKey(db_column='first_list', on_delete=django.db.models.deletion.CASCADE, related_name='first_list_data', to='text_app.tbltextlistdescription'),
        ),
        migrations.AlterField(
            model_name='tbltreedescription',
            name='is_deleted',
            field=models.BooleanField(db_comment='Флаг удаления дерева', default=False),
        ),
        migrations.AlterField(
            model_name='tbltreedescription',
            name='name',
            field=models.TextField(db_comment='Название проекта/дерева', max_length=200),
        ),
        migrations.AlterField(
            model_name='tbltreedescription',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner', db_comment='Владелец проекта/дерева', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tbltreedescription',
            name='public',
            field=models.BooleanField(db_comment='Публичный доступ к проекту/дереву', default=False),
        ),
        migrations.AlterField(
            model_name='tbltreedescription',
            name='second_list',
            field=models.ForeignKey(db_column='second_list', on_delete=django.db.models.deletion.CASCADE, related_name='second_list_data', to='text_app.tbltextlistdescription'),
        ),
    ]
