# Generated by Django 5.0.4 on 2024-05-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r_tree_app', '0002_alter_tbltreedescription_table_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltreedescription',
            name='build_status',
            field=models.TextField(db_comment='Статус сборки', max_length=200, null=True),
        ),
    ]
