# Generated by Django 5.0.4 on 2024-05-22 12:28

import picklefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r_tree_app', '0003_tbltreedescription_build_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbltreedescription',
            name='graph',
        ),
        migrations.AddField(
            model_name='tbltreedescription',
            name='graph_dot',
            field=models.TextField(blank=True, db_comment='Граф дерева решений', null=True),
        ),
        migrations.AddField(
            model_name='tbltreedescription',
            name='graph_pickle',
            field=picklefield.fields.PickledObjectField(db_comment='Бинарное дерево решений', editable=False, null=True),
        ),
    ]
