# Generated by Django 5.2.1 on 2025-10-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r_tree_app', '0004_remove_tbltreedescription_graph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltreedescription',
            name='many_sectors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tbltreedescription',
            name='sector_size',
            field=models.FloatField(default=0),
        ),
    ]
