# Generated by Django 5.2.1 on 2025-10-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r_tree_app', '0005_tbltreedescription_many_sectors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltreedescription',
            name='is_need_duo',
            field=models.BooleanField(db_comment='Флаг использования биграмм частей речи в дереве решений', default=True),
        ),
        migrations.AddField(
            model_name='tbltreedescription',
            name='is_need_separate',
            field=models.BooleanField(db_comment='Флаг использования разделителей унограмм в дереве решений', default=False),
        ),
        migrations.AddField(
            model_name='tbltreedescription',
            name='is_need_uno',
            field=models.BooleanField(db_comment='Флаг использования унограмм частей речи в дереве решения', default=False),
        ),
        migrations.AlterField(
            model_name='tbltreedescription',
            name='block_size',
            field=models.IntegerField(db_comment='Размер блока для расчета', default=0),
        ),
        migrations.AlterField(
            model_name='tbltreedescription',
            name='build_at',
            field=models.DateTimeField(db_comment='Дата сборки', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tbltreedescription',
            name='many_sectors',
            field=models.BooleanField(db_comment='Флаг использования циклических разделов', default=False),
        ),
        migrations.AlterField(
            model_name='tbltreedescription',
            name='sector_size',
            field=models.FloatField(db_comment='Размер сектора в разделители в процентах (0-100)', default=0),
        ),
    ]
