# Generated by Django 5.2.1 on 2025-10-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r_tree_app', '0006_tbltreedescription_is_need_duo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltreedescription',
            name='max_depth',
            field=models.IntegerField(db_comment='Максимальная глубина дерева решений', default=4),
        ),
    ]
