# Generated by Django 5.2.1 on 2025-10-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r_tree_app', '0007_tbltreedescription_max_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltreedescription',
            name='accuracy',
            field=models.FloatField(db_comment='Точность дерева решений', default=0),
        ),
    ]
