# Generated by Django 5.2.1 on 2025-10-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r_tree_app', '0008_tbltreedescription_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltreedescription',
            name='vector_size',
            field=models.IntegerField(db_comment='Размер вектора принятия решений', default=0),
        ),
    ]
