# Generated by Django 5.2.1 on 2025-11-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r_tree_app', '0009_tbltreedescription_vector_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltreedescription',
            name='removed_pos',
            field=models.TextField(db_comment='Перечень частей речи для исключения из дерева решений', default='[]'),
        ),
    ]
