# Generated by Django 5.2.1 on 2025-11-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r_tree_app', '0010_tbltreedescription_removed_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltreedescription',
            name='table1_size',
            field=models.IntegerField(db_comment='Число блоков текста первого набора', default=0),
        ),
        migrations.AddField(
            model_name='tbltreedescription',
            name='table2_size',
            field=models.IntegerField(db_comment='Число блоков текста второго набора', default=0),
        ),
        migrations.AlterField(
            model_name='tbltreedescription',
            name='is_need_separate',
            field=models.BooleanField(db_comment='Флаг использования разделителей униграмм в дереве решений', default=False),
        ),
        migrations.AlterField(
            model_name='tbltreedescription',
            name='is_need_uno',
            field=models.BooleanField(db_comment='Флаг использования униграмм частей речи в дереве решения', default=False),
        ),
    ]
