# Generated by Django 5.0.3 on 2024-04-08 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DictWord',
            new_name='TblDictWord',
        ),
        migrations.RenameModel(
            old_name='MenuItems',
            new_name='TblMenuItems',
        ),
        migrations.RenameModel(
            old_name='MenuParams',
            new_name='TblMenuParams',
        ),
        migrations.AlterModelTable(
            name='tbldictword',
            table='entries',
        ),
        migrations.AlterModelTable(
            name='tblmenuitems',
            table='menu_items',
        ),
        migrations.AlterModelTable(
            name='tblmenuparams',
            table='menu_params',
        ),
        migrations.AlterField(
            model_name='tblword',
            name='dictword2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='text_app.tbldictword2'),
        ),
    ]
