# Generated by Django 5.0.3 on 2024-04-22 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0002_tbldictword2_tblmenuitems2_tblmenuparams2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltext',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_data', to='text_app.tblauthor'),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='author2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author2_data', to='text_app.tblauthor'),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='author3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author3_data', to='text_app.tblauthor'),
        ),
    ]
