# Generated by Django 5.0 on 2025-04-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0003_alter_tbltext_author_alter_tbltext_author2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAuthorTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'author_types',
            },
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='attributions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='author2_type',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='author3_type',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='author_type',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='background',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='censorship',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='idkey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='magazine_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='magazine_section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='magazine_volume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='origin_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='pages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='short_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
