# Generated by Django 5.2.1 on 2025-11-05 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0004_tblauthortypes_alter_tbltext_attributions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltext',
            name='attributions',
            field=models.TextField(blank=True, db_column='ATTRIBUTIONS', null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='author',
            field=models.ForeignKey(blank=True, db_column='AUTHOR_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_data', to='text_app.tblauthor'),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='author2',
            field=models.ForeignKey(blank=True, db_column='AUTHOR2_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author2_data', to='text_app.tblauthor'),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='author2_type',
            field=models.IntegerField(blank=True, db_column='AUTHOR2_TYPE', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='author3',
            field=models.ForeignKey(blank=True, db_column='AUTHOR3_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author3_data', to='text_app.tblauthor'),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='author3_type',
            field=models.IntegerField(blank=True, db_column='AUTHOR3_TYPE', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='author_type',
            field=models.IntegerField(blank=True, db_column='AUTHOR_TYPE', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='author_verify',
            field=models.IntegerField(db_column='AUTHOR_VERIFY', default=0),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='background',
            field=models.ImageField(blank=True, db_column='BACKGROUND', max_length=1000, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='category',
            field=models.IntegerField(db_column='CATEGORY', default=0),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='censorship',
            field=models.TextField(blank=True, db_column='CENSORSHIP', null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='comment',
            field=models.TextField(blank=True, db_column='COMMENT', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='idkey',
            field=models.CharField(blank=True, db_column='IDKEY', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='inuse1',
            field=models.IntegerField(db_column='INUSE1', default=1),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='inuse2',
            field=models.IntegerField(db_column='INUSE2', default=0),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='magazine',
            field=models.ForeignKey(blank=True, db_column='MAGAZINE_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='text_app.tblmagazine'),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='magazine_no',
            field=models.CharField(blank=True, db_column='MAGAZINE_NO', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='magazine_section',
            field=models.CharField(blank=True, db_column='MAGAZINE_SECTION', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='magazine_volume',
            field=models.CharField(blank=True, db_column='MAGAZINE_VOLUME', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='origin_title',
            field=models.TextField(blank=True, db_column='ORIGIN_TITLE', null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='pages',
            field=models.CharField(blank=True, db_column='PAGES', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='publication_date',
            field=models.DateField(blank=True, db_column='PUBLICATION_DATE', null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='short_title',
            field=models.TextField(blank=True, db_column='SHORT_TITLE', null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='status',
            field=models.IntegerField(db_column='STATUS', default=0),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='syntax',
            field=models.IntegerField(db_column='SYNTAX', default=0),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='text_type',
            field=models.IntegerField(db_column='TEXT_TYPE', default=0),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='title',
            field=models.TextField(blank=True, db_column='TITLE', null=True),
        ),
        migrations.AlterField(
            model_name='tbltext',
            name='url',
            field=models.URLField(blank=True, db_column='URL', max_length=1000, null=True),
        ),
    ]
