# Generated by Django 5.0.3 on 2024-03-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('level', models.IntegerField(default=0)),
                ('researcher', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sys_users',
            },
        ),
    ]
